### Post a Category
POST http://localhost:8000/categories HTTP/1.1
content-type: application/json

{
    "name": "Leitende"
}
### Get one Category
GET http://localhost:8000/categories/id HTTP/1.1
content-type: application/json

### Get all Categories
GET http://localhost:8000/categories HTTP/1.1
content-type: application/json

### Update a Categorie
PUT http://localhost:8000/categories/62824fcc00d8c849809675d3 HTTP/1.1
content-type: application/json

{
    "color": "DarkSeaGreen"
}

### Delete one Categorie
Delete http://localhost:8000/categories/62824596b7de7a472c9d7343 HTTP/1.1
content-type: application/json
