### Post a Hall
POST http://localhost:8000/halls HTTP/1.1
content-type: application/json

{
    "name": "Halle C"
}
### Get one Hall
GET http://localhost:8000/halls/id HTTP/1.1
content-type: application/json

### Get all Halls
GET http://localhost:8000/halls HTTP/1.1
content-type: application/json

### Update a Hall
POST http://localhost:8000/halls HTTP/1.1
content-type: application/json

{
    "name": "Wildert"
}

### Delete one Hall
Delete http://localhost:8000/halls/id HTTP/1.1
content-type: application/json
