### Get Time Preview
GET http://localhost:8000/tournament/time-preview HTTP/1.1
content-type: application/json

### Get Table
GET http://localhost:8000/tournament/table HTTP/1.1
content-type: application/json

### Get Table Preview
GET http://localhost:8000/tournament/preview HTTP/1.1
content-type: application/json

### Get Ranking
GET http://localhost:8000/tournament/ranking HTTP/1.1
content-type: application/json

### Create Finals
GET http://localhost:8000/tournament/create-finals HTTP/1.1
content-type: application/json

### Add Referee
POST http://localhost:8000/tournament/referee HTTP/1.1
content-type: application/json

{
    "userId": "63601b4fde991ece04557de4",
    "gameId": "63602551af1e6f3197bec986"
}

### Assign Referees
POST http://localhost:8000/tournament/assign-referees HTTP/1.1
content-type: application/json
