@authToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVmODlkNjU0MTNlZmQ3NTk1OGI1OWUiLCJuaWNrbmFtZSI6ImFkbWluIiwicm9sZXMiOlsiQWRtaW4iXSwiaWF0IjoxNjY3MjA1NjY0LCJleHAiOjE2NjcyNDg4NjR9.fC_ECpYy79clV4esJL4bL0ueoBt4pVbliRxW0IvIMU0

### Post a User
POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "nickname": "Archim",
    "password": "Test"
}

### Login User
POST http://localhost:8000/users/login HTTP/1.1
content-type: application/json

{
    "nickname": "Archi",
    "password": "Test"
}
### Get one User
GET http://localhost:8000/users/id HTTP/1.1
content-type: application/json


### Get all Users
GET http://localhost:8000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### Update a User
PUT http://localhost:8000/users/635fa0507cbac718dddd7011 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "Admin"
}

### Delete one User
Delete http://localhost:8000/users/634fce9358d0a3a11767a262 HTTP/1.1
content-type: application/json
