@authToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzYwMWI0ZmRlOTkxZWNlMDQ1NTdkZTQiLCJuaWNrbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjY3MzkwMDk2LCJleHAiOjE2Njc0MzMyOTZ9.i7HVA3N15FAGDS0zc7brr5-ScoIjX8RdTOrieD6VCz4

### Post a User
POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "nickname": "Archim",
    "password": "Test"
}

### Login User
POST http://localhost:8000/users/login HTTP/1.1
content-type: application/json

{
    "nickname": "admin",
    "password": "Test"
}
### Get one User
GET http://localhost:8000/users/id HTTP/1.1
content-type: application/json


### Get all Users
GET http://localhost:8000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

### Update a User
PUT http://localhost:8000/users/635fa0507cbac718dddd7011 HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "Admin"
}

### Delete one User
Delete http://localhost:8000/users/634fce9358d0a3a11767a262 HTTP/1.1
content-type: application/json
